#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
profile="${SIGNALFORGE_PROFILE:-radeon-local}"
requested_backend="${SIGNALFORGE_EXECUTION_BACKEND:-auto}"
if [[ -n "${SIGNALFORGE_PERSIST_ROOT:-}" ]]; then
  persist_root="$SIGNALFORGE_PERSIST_ROOT"
elif [[ -d /workspace ]]; then
  persist_root="/workspace/signalforge-runtime"
else
  persist_root="$repo_root/.signalforge/radeon"
fi
generated_env="$persist_root/state/generated.env"

if [[ -f "$generated_env" && ! -L "$generated_env" ]]; then
  set -a
  # This file is generated by radeon_preflight.py and contains derived, non-secret values only.
  # shellcheck disable=SC1090
  source "$generated_env"
  set +a
fi

args=(
  --profile "$profile"
  --persist-root "$persist_root"
  --secrets-dir "$repo_root/.secrets"
  --report "$persist_root/state/preflight.json"
  --env-output "$generated_env"
  --model-source "${SIGNALFORGE_MODEL_SOURCE:-huggingface}"
  --backend "$requested_backend"
)
if [[ "${SIGNALFORGE_ACCEPT_GEMMA_LICENSE:-no}" == "yes" ]]; then
  args+=(--license-accepted)
fi
if [[ ! -f "$persist_root/models/.signalforge-model-ready.json" ]]; then
  args+=(--check-network)
fi

exec python3 "$repo_root/scripts/radeon_preflight.py" "${args[@]}"
