import type { Projection, Section } from "../types";
import { ArrowIcon, CheckIcon, DocumentIcon, ReceiptIcon, ShieldIcon } from "./Icons";
import { displayCompany } from "../format";

type Props = {
  projection: Projection;
  activeSection: string;
  onSection: (section: string) => void;
  onProof: (kind: "evidence" | "calculations", refs?: string[]) => void;
};

export function InsightPanel({ projection, activeSection, onSection, onProof }: Props) {
  const section = projection.sections.find((item) => item.section_type === activeSection) ?? projection.sections[0];
  const index = projection.sections.indexOf(section);
  return (
    <article className="insight-panel" aria-labelledby="section-title">
      <header className="insight-header">
        <div>
          <span className="chapter-index">Chapter {String(index + 1).padStart(2, "0")} / {String(projection.sections.length).padStart(2, "0")}</span>
          <h2 id="section-title">{section.title}</h2>
        </div>
        <div className="section-proof">
          <button onClick={() => onProof("evidence", section.evidence_refs)}><DocumentIcon /> {section.evidence_refs?.length ?? 0} sources</button>
          <button onClick={() => onProof("calculations", section.receipt_refs)}><ReceiptIcon /> {section.receipt_refs?.length ?? 0} receipts</button>
        </div>
      </header>
      <div className="section-prose">
        {paragraphs(section).map((paragraph, paragraphIndex) => <p key={`${section.section_type}-${paragraphIndex}`}>{paragraph}</p>)}
      </div>
      <div className="authority-strip">
        <ShieldIcon />
        <div><strong>Numerical authority preserved</strong><span>Financial values above are rendered from deterministic Go receipts, not generated by the language model.</span></div>
        <CheckIcon />
      </div>
      <footer className="chapter-controls">
        <button disabled={index === 0} onClick={() => onSection(projection.sections[index - 1]?.section_type)}>Previous</button>
        <span>{projection.companies.map((company) => displayCompany(company.label)).join(" versus ")}</span>
        <button disabled={index === projection.sections.length - 1} onClick={() => onSection(projection.sections[index + 1]?.section_type)}>Next <ArrowIcon /></button>
      </footer>
    </article>
  );
}

export function CaseNotes({ projection }: { projection: Projection }) {
  return (
    <section className="case-notes" aria-label="Research assumptions and limits">
      <ClaimAuthorityGuide />
      <NoteBlock title="Explicit assumptions" items={projection.assumptions ?? []} tone="assumption" />
      <NoteBlock title="Known limitations" items={projection.limitations ?? []} tone="limitation" />
      <NoteBlock title="Next diligence actions" items={projection.next_actions ?? []} tone="action" />
      {(projection.warnings?.length ?? 0) > 0 && (
        <details className="warning-ledger">
          <summary><span>System caveats</span><strong>{projection.warnings!.length} surfaced, none hidden</strong></summary>
          <ul>{projection.warnings!.map((warning, index) => <li key={`${warning.kind}-${warning.role_id ?? "system"}-${index}`}><span>{warning.kind.replaceAll("_", " ")}</span>{warning.text}</li>)}</ul>
        </details>
      )}
    </section>
  );
}

function ClaimAuthorityGuide() {
  const authorities = [
    ["Reported fact", "Bound to a dated evidence card from a filing, official market source, or governed dataset."],
    ["Management assertion", "Issuer guidance, plans, explanations, and risk statements remain attributed claims, not realized outcomes."],
    ["Deterministic calculation", "Computed by a versioned Go engine and released only with a successful receipt and invariants."],
    ["Model interpretation", "A challenged synthesis of authorized evidence; it remains interpretation rather than source fact."],
    ["Scenario assumption", "An explicit user or research premise listed below, never presented as an observed future path."],
    ["Unresolved hypothesis", "A question or causal possibility retained in limitations, caveats, or next diligence rather than asserted as fact."]
  ];
  return (
    <details className="claim-authority-guide">
      <summary><span>Claim authority key</span><strong>Six boundaries kept distinct</strong></summary>
      <div>
        {authorities.map(([label, meaning]) => (
          <article key={label}><strong>{label}</strong><p>{meaning}</p></article>
        ))}
      </div>
    </details>
  );
}

function NoteBlock({ title, items, tone }: { title: string; items: string[]; tone: string }) {
  if (items.length === 0) return null;
  return (
    <div className={`note-block ${tone}`}>
      <h3>{title}</h3>
      <ul>{items.map((item) => <li key={item}>{item}</li>)}</ul>
    </div>
  );
}

function paragraphs(section: Section) {
  return section.content.split(/\n\s*\n/).map((value) => value.trim()).filter(Boolean);
}
